version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npx @11ty/eleventy
artifacts:
  files:
    - '_site/*'